#!/bin/bash

cd /home/lufimtse/apps
tar czf eclipseBackups/eclipse$(date +'%Y.%m.%d_%H%M')_${1}.tar.gz eclipse
tar czf eclipseBackups/eclipse-workspace$(date +'%Y.%m.%d_%H%M')${1}.tar.gz eclipse-workspace
