#!/bin/bash
echo "Clean up of bindings"
set -x  # print info about every command that is executed.
cd ~/git/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.gtk.linux.x86_64 && \
git clean -xdf && \
git reset --hard && \

echo "Rebuild of bindings"
cd ~/git/eclipse.platform.swt/bundles/org.eclipse.swt/bin/library && \
./build.sh -gtk-all install  

