#!/bin/bash
rm -rf ~/runtime-tmp/

/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-7.b14.fc24.x86_64/bin/java -Declipse.pde.launch=true -Dfile.encoding=UTF-8 -classpath /home/lufimtse/apps/eclipse/plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar org.eclipse.equinox.launcher.Main -launcher /home/lufimtse/apps/eclipse/eclipse -name Eclipse -showsplash 600 -product org.eclipse.sdk.ide -data /home/lufimtse/workspace/../runtime-tmp -configuration "file:/home/lufimtse/workspace/.metadata/.plugins/org.eclipse.pde.core/tmp g3/" -dev "file:/home/lufimtse/workspace/.metadata/.plugins/org.eclipse.pde.core/tmp g3/dev.properties" -os linux -ws gtk -arch x86_64 -nl en_CA -consoleLog

