#!/bin/bash
# Running yed via java 8. Installed via: http://www.if-not-true-then-false.com/2014/install-oracle-java-8-on-fedora-centos-rhel/
# I just downloaded the jre and installed via "rpm -Uvh ...". None of the other stuff. 

/usr/java/latest/jre/bin/java -jar ~/apps/yed/yed.jar 
