#!/usr/bin/env python
# toclip 
# NOTE: 'xsel' has to be installed from dnf for this to work.
 
# tocb.py ("to clipboard(s)") << old name. 
#src: https://pythonadventures.wordpress.com/2011/03/05/copy-string-to-x-clipboards/
 
import sys
import subprocess
 
###############################################
 
def text_to_clipboards(text):
    # "primary":
    xsel_proc = subprocess.Popen(['xsel', '-pi'], stdin=subprocess.PIPE)
    xsel_proc.communicate(text)
    # "clipboard":
    xsel_proc = subprocess.Popen(['xsel', '-bi'], stdin=subprocess.PIPE)
    xsel_proc.communicate(text)
 
###############################################
 
stuff = sys.stdin.read()
text_to_clipboards(stuff)
