#!/bin/bash
export SWT_WARNINGS=1
if [[ $1 == "2" ]]; then
	export SWT_GTK3=0
	echo "gtk 2 mode activated"
else
	export SWT_GTK3=1
fi
if [[ $1 == "w" ]]; then
	export GDK_BACKEND=wayland
	echo "wayland backend"
else
	export GDK_BACKEND=x11
	echo "x11 backend"
fi
export SWT_WEBKIT2=1
export SWT_LIB_VERSIONS=1
# export C_INCLUDE_PATH=$C_INCLUDE_PATH:/home/lufimtse/git/LDT/include
~/apps/eclipse/eclipse
