#!/bin/bash
inotifywait -m /home/lufimtse/tmp -e create -e moved_to |
    while read path action file; do
        echo "The file '$file' appeared in directory '$path' via '$action'"
        # do something with the file
	cd "/home/lufimtse/git/eclipse.platform.swt/tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit"
    	./runjUnits.sh
    done
