#!/bin/bash

# Remove old SO files.
rm ~/.swt/lib/linux/x86_64/*
rm ~/git/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.gtk.linux.x86_64/*.so

# build new once
swtjnibuild.sh

# copy so files to swt library
cd ~/git/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.gtk.linux.x86_64/
cp $(find . | grep .so) ~/.swt/lib/linux/x86_64/


