#!/bin/bash
cd "/home/lufimtse/git/LDT/pomlog"
TODAY=$(date +'%Y-W%V-%m%b-%d%a')

echo -n "Goal?: "
read GOAL

for i in `seq 1 60`;
do
	echo -n "$i "
	read -t 1 ANSW
	if [[ "$ANSW" == "c" ]]; then
		echo "Pomodoro Cancled"
		exit
	elif [[ "$ANSW" == "f" ]]; then
		echo "Pomodoro finished early"
		break
	fi

	# non-intrusive message about pomodoro finish.

	if [[ $i == '24' ]]; then
		notify-send "Pomodoro : 24 minute mark"
	fi

	if [[ $i == '25' ]]; then 
		notify-send "Pomodoro : Completed!"
	fi

	if [[ $i == '30' ]]; then
		notify-send "Pomodoro : Overkill!" "30 minute mark. You should stop working now..."
	fi
	if [[ $i == '40' ]]; then
		notify-send "Pomodoro : Masterkill!" "40 minute mark. You are going into overdrive..."
	fi

	if [[ $i == '59' ]]; then
		notify-send "Pomodoro : END" "59 minute mark, Pomodoro timer will shutdown in a min...."
	fi

done
MIN_COMPLETED=$i
echo -n "Actual?: "
read ACTUAL

# Pomodor line design:
# (count) (minutes) Goal: (my goal) Actual: (my actulal)

COUNT=$(wc -l "$TODAY" | cut -f1 -d" ")
COUNT=`expr $COUNT + 1`
clear
echo "$COUNT $MIN_COMPLETED $(date +'%I:%M %p') Goal: $GOAL         ACTUAL: $ACTUAL" | tee -a "$TODAY"
 
SUM_MINS=$(cat "$TODAY" | cut -f2 -d" " | paste -sd+ - | bc)
echo "Today Poms: $COUNT , Sum mins: $SUM_MINS"

# http://unix.stackexchange.com/questions/191293/bash-function-to-read-user-input-or-interrupt-on-timeout
# http://stackoverflow.com/questions/12199631/convert-seconds-to-hours-minutes-seconds
