#!/bin/bash
rm /tmp/pomlog.dat
cd /home/lufimtse/ldt/pomlog2
for i in $(ls /home/lufimtse/ldt/pomlog2); do echo "$i $(cat $i | wc -l)" >> /tmp/pomlog.dat; done
gnuplot -p /home/lufimtse/git/LDT/path/pomlog.plot
