#!/bin/bash
# For piping-into ansible output that prints\nStuff\nLike\nThis.
# 2018
# Inspiration https://stackoverflow.com/questions/34188167/ansible-print-message-debug-msg-line1-n-var2-n-line3-with-var3
while read line
do
  echo $line | sed 's/\\n/\n/g'
done < "${1:-/dev/stdin}"
