#!/bin/bash
# Script I found and hacked from: 
# http://handybashscripts.blogspot.ca/2012/01/simple-timer-with-progress-bar.html

ICON=/usr/share/app-info/icons/fedora/128x128/0ad.png
SOUND=/usr/share/sounds/gnome/default/alerts/glass.ogg

COUNT="$1"
shift
TEXT="$*"
# Determine number of seconds to count down from depending on input suffix.
case "${COUNT: -1}" in
    "S" | "s" ) COUNT=$(echo $COUNT | sed -s "s/[Ss]//") ;;
    "M" | "m" ) COUNT=$(echo $COUNT | sed -s "s/[Mm]//"); ((COUNT*=60)) ;;
    "H" | "h" ) COUNT=$(echo $COUNT | sed -s "s/[Hh]//"); ((COUNT*=3600)) ;;
    *	      ) COUNT=$((COUNT*=60))  # use minutes as default.
	# *         ) echo "Use the form of 10s or 5m or 2h.No decimals allowed."
esac
echo $COUNT
START=$COUNT                                              # Set a start point.

until [ "$COUNT" -eq "0" ]; do                            # Countdown loop.
    ((COUNT-=1))                                          # Decrement seconds.
    PERCENT=$((100-100*COUNT/START))                      # Calc percentage.
    echo "#Time remaining$(echo "obase=60;$COUNT" | bc)"  # Convert to H:M:S.
    echo $PERCENT                                         # Outut for progbar.
    sleep 1
done | yad --geometry=200x50+1970+3050 --skip-taskbar --no-focus --on-top --undecorated --title "Egg Timer" --progress --percentage=0 --text="$TEXT"\
    --window-icon=$ICON --button="gtk-close:1" --auto-close                     # Progbar/time left.
if [ $? = 1 ]; then exit $?; fi
echo $?

########### Notifications
# Regular
#notify-send -i $ICON "~~Timer Finished~~"         # Attention finish!

# Custom splash
yad --no-foucus --timeout=10 --splash --on-top --skip-taskbar \
	--image=$ICON --text="$TEXT" --timeout-indicator=bottom &

########### Sounds
mplayer "$SOUND"
