#!/bin/bash
echo "rsyncing swt binaries"
rsync -rtu --delete-delay /home/lufimtse/host/git/eclipse.platform.swt.binaries/ ~/git/eclipse.platform.swt.binaries/
echo "rsyncing swt sources"
rsync -rtu --delete-delay /home/lufimtse/host/git/eclipse.platform.swt/ ~/git/eclipse.platform.swt/
