#!/bin/bash

# activate FaceTime front Webcam.
# https://github.com/patjak/bcwc_pcie/wiki/Get-Started
# sudo modprobe facetimehd   #not working atm :'-(

# Launch some background stuff in x11:
export GDK_BACKEND=x11
autokey-gtk &
yEd &
e &
atom &
