#!/bin/bash

# activate FaceTime front Webcam.
# https://github.com/patjak/bcwc_pcie/wiki/Get-Started
sudo modprobe facetimehd   # Last compiled for 4.13.0-0.rc3.git1.2.fc27.x86_64.
			   # If updating kernel, need to re-compile.
xmodmap ~/.Xmodmap 

