
* Anniversaries
%%(org-anniversary 2014  7 16) Martha's birthday
%%(org-anniversary 2014  3  2) the mehl returns
* 2015
** 2015-02 February
*** 2015-02-25 Wednesday
**** Configured org diary today.
<2015-02-25 Wed>
This took a non-trivial amount of time. 

It was initially unclear as to wheter I should use journal packages or the build-in stuff. 
The journal packages were more designed for 'per-day' basis. 
Where as I wanted something more like a single file with many entries like this.

Let's see how things work out.
*** 2015-02-26 Thursday
**** Trouble making a function that work that has an 'enum' paramater. (solved)
<2015-02-26 Thu>
It turns out it was a combination of Typo + function did 
not exist in Gtk and there was no 'since xyz' tag in the gtk docu
*** 2015-02-27 Friday
**** Need to go to bed on time [d]
<2015-02-27 Fri>
I've been going to bed rather late in the last couple of days.. 
Need to make sure I go to bed on time.
** 2015-03 March
*** 2015-03-02 Monday
**** Drank a cup of coffee today :-/
<2015-03-02 Mon>
*** 2015-03-12 Thursday
**** Need more sleep
<2015-03-12 Thu>
I haven't been getting much sleep latley. I've been patching myself up with decaf coffee
that actually seem to have some coffe inside of it.

I've become somewhat of a useless zombie. Can't think, can't learn, can't be productivle.

I should get more sleep and avoid coffee.
*** 2015-03-20 Friday
**** Pom 30 min try
<2015-03-20 Fri>
I'd like to try to do a 30 minute pomodoro again. 
Let's try to do it for a week and see what happens.
***** DONE Followup, how was 30 pomodoro mins like?
CLOSED: [2015-05-25 Mon 11:58] 
:LOGBOOK:  
- State "DONE"       from "WAIT"       [2015-05-25 Mon 11:58]
- State "WAIT"       from "HOLD"       [2015-05-25 Mon 11:58]
- Note taken on [2015-05-25 Mon 11:58] \\
  Nah, 30 mins didn't work that well. I seem to loose focus.
- Note taken on [2015-04-30 Thu 12:30] \\
  I do feel that 30 mins might be a bit too long.
  But I seem to have adjusted to it ok. Let's try a bit more.
- Note taken on [2015-04-13 Mon 13:58] \\
  I seem to have adjusted myself to it. 
  But let's see further. Maybe set a timer that decreases is dynamically throughout the day.
- Note taken on [2015-04-02 Thu 14:38] \\
  30 seems to work if you stick with ti.
:END:      

** 2015-07 July
*** 2015-07-15 Wednesday
**** Reminder: Make cake for Martha's birthday.
<2015-07-15 Wed>
